-- 2016 yýlýndaki mülk tiplerinin ortalama fiyatlarýný aylar þeklinde gösteren sorgu

SELECT 
    Type_,
    ISNULL(FORMAT(AVG(CASE WHEN DATEPART(MONTH, Date_) = 1 THEN Price END), '#,0.'),0) AS 'AVG PRICE IN JAN 2016',
    ISNULL(FORMAT(AVG(CASE WHEN DATEPART(MONTH, Date_) = 2 THEN Price END), '#,0'),0) AS 'AVG PRICE IN FEB 2016',
    ISNULL(FORMAT(AVG(CASE WHEN DATEPART(MONTH, Date_) = 3 THEN Price END), '#,0'),0) AS 'AVG PRICE IN MAR 2016',
    ISNULL(FORMAT(AVG(CASE WHEN DATEPART(MONTH, Date_) = 4 THEN Price END), '#,0'),0) AS 'AVG PRICE IN APR 2016',
    ISNULL(FORMAT(AVG(CASE WHEN DATEPART(MONTH, Date_) = 5 THEN Price END), '#,0'),0) AS 'AVG PRICE IN MAY 2016',
    ISNULL(FORMAT(AVG(CASE WHEN DATEPART(MONTH, Date_) = 6 THEN Price END), '#,0'),0) AS 'AVG PRICE IN JUN 2016',
    ISNULL(FORMAT(AVG(CASE WHEN DATEPART(MONTH, Date_) = 7 THEN Price END), '#,0'),0) AS 'AVG PRICE IN JUL 2016',
    ISNULL(FORMAT(AVG(CASE WHEN DATEPART(MONTH, Date_) = 8 THEN Price END), '#,0'),0) AS 'AVG PRICE IN AUG 2016',
    ISNULL(FORMAT(AVG(CASE WHEN DATEPART(MONTH, Date_) = 9 THEN Price END), '#,0'),0) AS 'AVG PRICE IN SEP 2016',
    ISNULL(FORMAT(AVG(CASE WHEN DATEPART(MONTH, Date_) = 10 THEN Price END), '#,0'),0) AS 'AVG PRICE IN OCT 2016',
    ISNULL(FORMAT(AVG(CASE WHEN DATEPART(MONTH, Date_) = 11 THEN Price END), '#,0'),0) AS 'AVG PRICE IN NOV 2016',
    ISNULL(FORMAT(AVG(CASE WHEN DATEPART(MONTH, Date_) = 12 THEN Price END), '#,0'),0) AS 'AVG PRICE IN DEC 2016'
FROM 
    melbourne_housing
WHERE 
    DATEPART(YEAR, Date_) = 2016
GROUP BY 
    Type_


